### ISSUE TITLE
Bcrypt 3.1.7 - Cannot load file on Windows

### ISSUE THREAD

**Issue by miguelpeniche** [bcrypt-ruby/bcrypt-ruby#102]
Bcrypt stoped working for everything i am using in my app, in my case gems like [Devise](https://github.com/plataformatec/devise) and [Friendly_id](https://github.com/norman/friendly_id) are dependant of _bcrypt_, and them are not working anymore.

For the purpose of showing the error to you, i just create a new app named `pr`, uncomment the Gemfile line

``` ruby
gem 'bcrypt', '~> 3.1.7'
```

Then run command

``` ruby
bundle install
```

And trying to start the server 

``` ruby
rails s
```

It explodes bad time! With the error

> C:/Ruby21/lib/ruby/gems/2.1.0/gems/bcrypt-3.1.7-x86-mingw32/lib/bcrypt.rb:16:in `require': cannot load such file -- bcrypt_ext (LoadError)

This is the screenshot

![captura de pantalla 2014-10-22 17 27 57](https://cloud.githubusercontent.com/assets/3253845/4745492/fd49aed0-5a3a-11e4-9da6-300ec9f887b0.png)

I am using the next:
- Window 7 64 bits system
- Rails 4.1.6
- ruby 2.1.3p242 (2014-09-19 revision 47630) [i386-mingw32]

Hope there is some fix for this issue soon.

**Comment by gilbertc77** [comment]
Got some error related to bcrypt when running rails s on win8.1 64bit, ruby 2.2.2, rails 4.2.1
![bcypt_ext error](https://cloud.githubusercontent.com/assets/4209214/7675382/7cd4dc88-fd6a-11e4-86aa-42c1772daadd.png)

**Comment by ccoenen** [comment]
very same thing here [Windows 8.1 64bit, ruby 2.2.2p95 32bit from rubyinstaller, Devkit loaded]. The error can be reproduced in irb without rails:

```
> gem install bcrypt
Fetching: bcrypt-3.1.10-x86-mingw32.gem (100%)
Successfully installed bcrypt-3.1.10-x86-mingw32
1 gem installed

C:\Users\user\workspace\project (master)
> irb
irb(main):001:0> require 'bcrypt'
LoadError: cannot load such file -- 2.2/bcrypt_ext
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Tools/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-ruby-3.0.1-x86-mingw32/lib/bcrypt_ext.rb:2:in `<top (required)>'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Tools/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
```

**Comment by Kalinon** [comment]
I know this is closed, but i encountered the same error on bcrypt 3.1.10 

Environment: 

```Windows 10 x64
bcrypt (3.1.10 x64-mingw32)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
Rails 4.2.5```

```rake aborted!
LoadError: cannot load such file -- bcrypt_ext
C:/Users/***/Documents/***/app/services/create_admin_service.rb:4:in `block in call'
C:in `find_or_create_by!'
C:/Users/***/Documents/***/app/services/create_admin_service.rb:3:in `call'
C:/Users/***/Documents/***/db/seeds.rb:8:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
LoadError: cannot load such file -- 2.2/bcrypt_ext
C:/Users/***/Documents/***/app/services/create_admin_service.rb:4:in `block in call'
C:in `find_or_create_by!'
C:/Users/***/Documents/***/app/services/create_admin_service.rb:3:in `call'
C:/Users/***/Documents/***/db/seeds.rb:8:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)```

**Comment by pranjal815** [comment]
I don't know but this is very strange. Whenever i mentioned following code in my Gemfile rails server stops working and when I comment the code it is working. I tried installing , updating and everything but bcrypt seems to be not working for me.

The code that I mentioned in the gem file is as follows:
gem 'bcrypt', '~> 3.1.9'

If I comment or delete the above line then "rails s" command is working.

I am using devise for authentication but when I entered username and password i get "LoadError in Devise::SessionsController#create" error in the web console in the rails server log I get "LoadError (cannot load such file -- bcrypt_ext):" error. Following is the screenshot of the error.
![screencapture-localhost-3000-authors-sign_in-1487686213516](https://cloud.githubusercontent.com/assets/3872393/23168284/4cf7e8c6-f80d-11e6-9c99-ec2e07a7cafa.png)

**Comment by ccoenen** [comment]
@pranjal815 this is a quite old ticket, you're not very likely to get help in those cases. I would always open a new ticket unless it's very much the same thing. Also, this would be better suited for Stackoverflow's Q&A Style questions rather than GitHubs Issues.

Try adding `'3.1.9'` with no `~>` to your `Gemfile`, this will freeze it to a specific version. Then do a `bundle install`.

Right now, you're running bcrypt 3.1.11 which may or may not be broken _again_. (you can tell from the path in your stacktrace, 5th and 6th line).

The leading `~>` gives bundler some leeway in choosing a version for you. This is described in the [bundler docs](http://bundler.io/gemfile.html#gemfiles).

**Comment by ladyruby723** [comment]
@pranjal815  I had a very similar issue, and adding the github version of bcrypt to my Gemfile seemed to fix the problem. :)

gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'

**Comment by dafeed** [comment]
@ladyruby723   I made an account just to thank you.  I'm going through Lynda.com's Ruby Course on Windows 7 and bcrypt wasn't working at all.  Just using the latest version of bcrypt made it so I couldn't use the rails server, couldn't create users in the console, nothing.  So I googled around like crazy for over 3 hours and tried all the different "solutions" like changing the platform to ruby, using a different version, blah blah blah.  But no matter what I did, the password_digest would never work.  I could add a password but it wouldn't encrypt it.  UNTIL I did what you said.  I uninstalled all the bcrypt and bcyrpt-ruby gems and then added the line you provided into the gemfile and then ran bundle install and holy crap, everything worked after that.  So again, thank you so much for putting this here.  For whatever reason it seems the github version is happy on my windows machine.  WOOT!

**Comment by cfkwok** [comment]
@ladyruby723 Thank you sooo much!!! I was about to dual boot Linux here...

**Comment by ericremer** [comment]
@ladyruby723 Thank you... everything else failed, but your solution worked!

**Comment by TheHeavenlyDao** [comment]
@ladyruby723 THANK YOU! I've been looking for a solution for so long, but your solution worked! Thank you very much!

**Comment by gaumondia** [comment]
@ladyruby723 I'm going crazy on this one. I tried everything I could find including your line and this is what came out of it. What should I try next? Thanks in advance :)

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

>bundle install
Fetching https://github.com/codahale/bcrypt-ruby.git

Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby23-x64
/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd4a2b4422
9a6546ff6af" --bare --no-hardlinks --quiet` due to error (2/4): Errno::ENOENT No
 such file or directory - git clone "https://github.com/codahale/bcrypt-ruby.git
" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f
096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet
Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby23-x64
/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd4a2b4422
9a6546ff6af" --bare --no-hardlinks --quiet` due to error (3/4): Errno::ENOENT No
 such file or directory - git clone "https://github.com/codahale/bcrypt-ruby.git
" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f
096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet
Retrying `git clone "https://github.com/codahale/bcrypt-ruby.git" "C:/Ruby23-x64
/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f096661bd4a2b4422
9a6546ff6af" --bare --no-hardlinks --quiet` due to error (4/4): Errno::ENOENT No
 such file or directory - git clone "https://github.com/codahale/bcrypt-ruby.git
" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-ruby-4da4473665a7f
096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet
--- ERROR REPORT TEMPLATE ------------------------------------------------------
-
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `C:/Ruby23-x64/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to... finally install a version of bcrypt that would work

- **What happened instead?**

  Instead, what happened was... the error I'm pasting here

- **Have you tried any solutions posted on similar issues in our issue tracker,
stack overflow, or google?**

  I tried... BCrypt 3.1.11 (x86-mingw32): cannot load such file -- bcrypt_ext #149

- **Have you read our issues document, https://github.com/bundler/bundler/blob/m
aster/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
Errno::ENOENT: No such file or directory - git clone "https://github.com/codahal
e/bcrypt-ruby.git" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/cache/bundler/git/bcrypt-r
uby-4da4473665a7f096661bd4a2b44229a6546ff6af" --bare --no-hardlinks --quiet
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:162:in ``'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:162:in `block (2 levels) in git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:239:in `block in capture_and_filter_stderr'
  C:/Ruby23-x64/lib/ruby/2.3.0/tempfile.rb:295:in `open'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:237:in `capture_and_filter_stderr'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:162:in `block in git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/shared_helpe
rs.rb:73:in `with_clean_git_env'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:161:in `git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:153:in `block in git_retry'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/retry.rb:39:
in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/retry.rb:29:
in `attempt'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:152:in `git_retry'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git/g
it_proxy.rb:104:in `checkout'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git.r
b:296:in `fetch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/source/git.r
b:155:in `specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:723:in `block in converge_locked_specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:712:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:712:in `converge_locked_specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:245:in `resolve'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:176:in `specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/definition.r
b:164:in `resolve_remotely!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/installer.rb
:226:in `resolve_if_need'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/installer.rb
:78:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/installer.rb
:24:in `install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/cli/install.
rb:70:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/cli.rb:181:i
n `block in install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/settings.rb:
99:in `temporary'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/cli.rb:180:i
n `install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/vendor/thor/
lib/thor/command.rb:27:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/vendor/thor/
lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/vendor/thor/
lib/thor.rb:359:in `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/cli.rb:20:in
 `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/vendor/thor/
lib/thor/base.rb:440:in `start'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/cli.rb:11:in
 `start'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/exe/bundle:32:in `block
in <top (required)>'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/friendly_err
ors.rb:121:in `with_friendly_errors'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/exe/bundle:24:in `<top (
required)>'
  C:/Ruby23-x64/bin/bundle:22:in `load'
  C:/Ruby23-x64/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.4
Rubygems  2.6.10
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
GEM_HOME  C:/Ruby23-x64/lib/ruby/gems/2.3.0
GEM_PATH  C:/Ruby23-x64/lib/ruby/gems/2.3.0;C:/Users/Gaumond/.gem/ruby/2.3.0
Git       not installed
Platform  x64-mingw32
OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
```
```

--- TEMPLATE END ---------------------------------------------------------------
-

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clon
e+%22https+%2F%2Fgithub.com%2Fcodahale%2Fbcrypt-ruby.git%22+%22C+%2FRuby23-x64%2
Flib%2Fruby%2Fgems%2F2.3.0%2Fcache%2Fbundler%2Fgit%2Fbcrypt-ruby-4da4473665a7f09
6661bd4a2b44229a6546ff6af%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by ccoenen** [comment]
I sympathise with everyone who has problems. I really do. I had my fair share myself. This ticket is not the place to get your issues fixed. **Open a new ticket with your specific problem** or post them to stackoverflow.

For one thing: this ticket is *closed*. Sadly, Github only shows this at the very top of the ticket, not at the place where you're likely to start reading. It only gets attention from people who are for some reason still subscribed to it. The developers very likely don't monitor closed tickets.

Another reason, why this is the wrong ticket: It is also about a different topic for the most part. At the very least because the versions are different. Probably also because your version of ruby today is not the same it was three years ago.

The Third reason is this: the devs don't see your problem (for the reasons above), so they can't acknowledge that bcrypt is one of the major stumbling blocks for ruby (on rails) newcomers. I've been lucky enough to be instructor in four different Ruby beginners events. A large portion of the participants are windows users. Pretty much all of them run into problems like yours. This will only get fixed if these problems are reported. Every new problem deserves a new ticket.

**Comment by Klashe** [comment]
ladyRudy Thank you. It worked like charm.

**Comment by farzam7777** [comment]
@ladyruby723 Thank you so much. Your solution worked for me.

**Comment by steph1793** [comment]
Thank you a lot @ladyruby723 . It also worked for me after 7 hours trying to fix this.

**Comment by franbach** [comment]
Thank you! @ladyruby723

**Comment by Ryanrj** [comment]
@ladyruby723 Thank  you!!

**Comment by ksb777** [comment]
I think nobody can solve this problem.......I did everything to solve this problem but bcrypt's issue is not solved.
damn issue.
