### ISSUE TITLE
Security issue in secrets longer than 72 characters

### ISSUE THREAD

**Issue by frznvm0** [bcrypt-ruby/bcrypt-ruby#47]
Version info:

```
Linux 3.4.8-1-ARCH x86_64 GNU/Linux
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
bcrypt-ruby master (ef50fe960d4dc50eb1df76fbc18a312a43e5c07d) pulled from git://github.com/codahale/bcrypt-ruby.git
```

`BCrypt::Password#==` returns true even if only the first 72 characters of the secret are valid.

Example:

``` ruby
require 'bcrypt'
secret1 = ('a' * 72) + 'test'
secret2 = ('a' * 72) + 'fail'
crypted = BCrypt::Password.create(secret1)
p crypted == secret2 # => true
```

This may not seem really dangerous, but if somebody uses their own salting system in addition to BCrypt's (the secrets contain a salt as well), this can be an issue.

An example of a vulnerable system: let's say somebody uses BCrypt to hash `(password + salt + pepper)`, where `password` is the user's password, `salt` is the 128 character long extra salt and `pepper` is a global value only available to application code. If the database gets hacked, the hacker does not have to get access to the source code of the application to get the pepper, because he only has to compute the first 80 characters, which eliminates the security factor of the pepper entirely.

**Comment by jomo** [comment]
Even without custom salting, this is still a security concern.

For a simplified proof of concept, consider someone using the password
`000000000000000000000000000000000000000000000000000000000000000000000000kEGF8vY6rR78kOb65WCbRw`.
According to [zxcvbn](https://github.com/dropbox/zxcvbn) this is a _really_ good password that's practically impossible to crack.
However, an attacker would only need to crack `000000000000000000000000000000000000000000000000000000000000000000000000`,
which could be cracked in seconds.

The culprit is that bcrypt (eksblowfish) has an upper limit of 72 characters (56b) for passwords, anything else is cut off.

This has also been discussed in https://github.com/rails/rails/issues/14591, which led to setting a limit of 72 characters when using `has_secure_password`.

I think it would be best if BCrypt would raise an error if the password is longer than 72 characters. Can this be re-opened?
